import Foundation

/// The sound the reset alarm plays when a previously exhausted quota
/// becomes usable again.  Picker value, raw value, and display label
/// are the same as the macOS app so a sound picked on either device
/// reads sensibly on the other (the App Group defaults key is
/// `alarmSound`, mirroring the macOS `ResetAlarmManager` storage).
///
/// This file is intentionally a near-verbatim mirror of
/// `Sources/QuotaCore/ResetAlarmSound.swift`.  The iOS app target does
/// not import QuotaCore: `Package.swift` declares QuotaCore for macOS
/// only, and the library reads the current user's home directory and
/// spawns helper processes, neither of which exists on iOS.  Making
/// QuotaCore multiplatform is a real refactor and is tracked separately.
/// Until then the two enums share a raw-value contract, and
/// `Tests/QuotaCoreTests/ResetAlarmSoundParityTests.swift` fails the
/// build if either side adds a case or diverges.  If either side adds a
/// new case, the other gets it alongside.
public enum ResetAlarmSound: String, CaseIterable, Codable, Sendable {
    case systemDefault = "system.default"
    case glass = "Glass"
    case submarine = "Submarine"
    case frog = "Frog"
    case blow = "Blow"
    case bottle = "Bottle"
    case tink = "Tink"
    case sosumi = "Sosumi"
    case silent = "silent"

    /// Owner-facing picker label, sentence case per fleet UI rule for
    /// value text with Title Case preserved where macOS's system sound
    /// catalogue capitalises the name.
    public var displayName: String {
        switch self {
        case .systemDefault: return "Default chime"
        case .glass: return "Glass"
        case .submarine: return "Submarine"
        case .frog: return "Frog"
        case .blow: return "Blow"
        case .bottle: return "Bottle"
        case .tink: return "Tink"
        case .sosumi: return "Sosumi"
        case .silent: return "Silent (banner only)"
        }
    }

    /// Short prose justifying the choice for an owner who has not
    /// heard the system sounds since macOS Ventura.
    public var pickerDetail: String {
        switch self {
        case .systemDefault: return "The platform's standard alert tone."
        case .glass: return "A bright tap — easy to hear in a quiet room."
        case .submarine: return "A low, longer tone — easy to hear through headphones."
        case .frog: return "A short ribbit — distinctive but unobtrusive."
        case .blow: return "An airy puff — barely registers if the office is loud."
        case .bottle: return "A cork pop — punchy and brief."
        case .tink: return "A small bell — light, single-tone."
        case .sosumi: return "The classic Mac alert."
        case .silent: return "Banner only — no sound plays; the row in Glance still highlights."
        }
    }

    public var isAudible: Bool { self != .silent }

    /// The bundled audio file that carries this tone on iOS, or `nil` for
    /// `systemDefault` (the platform chime) and `silent` (no chime).
    ///
    /// iOS `UNNotificationSound(named:)` resolves only the app's own bundled
    /// audio, so the macOS system sound names this enum carries cannot resolve
    /// there and a real reset alert is silent.  These files are generated by
    /// `scripts/generate-alarm-sounds.py`.
    ///
    /// Must stay identical to `Sources/QuotaCore/ResetAlarmSound.swift`;
    /// `Tests/QuotaCoreTests/ResetAlarmSoundParityTests.swift` fails the build
    /// if the two drift.
    public var bundledAssetName: String? {
        switch self {
        case .systemDefault, .silent: return nil
        case .glass: return "alarm-glass"
        case .submarine: return "alarm-submarine"
        case .frog: return "alarm-frog"
        case .blow: return "alarm-blow"
        case .bottle: return "alarm-bottle"
        case .tink: return "alarm-tink"
        case .sosumi: return "alarm-sosumi"
        }
    }

    public static let bundledAssetExtension = "wav"

    /// Convenience for the iOS picker ordering.  Same order as on Mac.
    public static let defaultPickerOrder: [ResetAlarmSound] = [
        .systemDefault, .blow, .bottle, .frog, .glass, .sosumi, .submarine, .tink, .silent,
    ]
}
